---
sudo: required
env:
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init

services:
  - docker

script:
  - ./build

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
